# Generated by Django 5.1.4 on 2024-12-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login_rename_taskdesc_task_taskdesc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logins',
        ),
    ]
