# Generated by Django 5.1.4 on 2024-12-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_signups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logins',
        ),
        migrations.DeleteModel(
            name='signups',
        ),
    ]
